[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor options
monitor_speed = 115200

; Library dependencies
lib_deps =
    ; Firebase and WiFi
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14
    
    ; Sensors and Actuators
    miguelbalboa/MFRC522 @ ^1.4.11
    beegee-tokyo/DHT sensor library for ESPx @ ^1.19
    madhephaestus/ESP32Servo @ ^3.0.5
    
    ; Display
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

; Enable testing framework
test_framework = unity